num1 = input('Digite um número: ')
print(num1)
print(type(num1))
print('É alfanumérico: ', num1.isalnum())
print('É numérico: ', num1.isnumeric())
print('É alfabético: ', num1.isalpha())
print('É caixa alta: ', num1.isupper())
print('É caixa baixa: ', num1.islower())
print('É espaço: ', num1.isspace())
